import type { SundayEntry } from '../types'

// Year C — Gospel of Luke — Advent 2024 – Christ the King 2025
// Sources: USCCB Lectionary for Mass, NABRE edition
const yearC: SundayEntry[] = [
  // ADVENT
  {
    slug: '1st-sunday-advent',
    sundayName: '1st Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Luke 21:25-28, 34-36',
    firstReadingRef: 'Jer 33:14-16',
    psalmRef: 'Ps 25',
    secondReadingRef: '1 Thess 3:12–4:2',
    oneLineTheme: 'Signs in the sky — stand erect; your redemption is near',
  },
  {
    slug: '2nd-sunday-advent',
    sundayName: '2nd Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Luke 3:1-6',
    firstReadingRef: 'Bar 5:1-9',
    psalmRef: 'Ps 126',
    secondReadingRef: 'Phil 1:4-6, 8-11',
    oneLineTheme: 'John preaches in the desert — "All flesh shall see the salvation of God"',
  },
  {
    slug: '3rd-sunday-advent',
    sundayName: '3rd Sunday of Advent (Gaudete)',
    season: 'Advent',
    gospelRef: 'Luke 3:10-18',
    firstReadingRef: 'Zeph 3:14-18a',
    psalmRef: 'Isa 12:2-3, 4, 5-6',
    secondReadingRef: 'Phil 4:4-7',
    oneLineTheme: '"What should we do?" — John\'s concrete call to share, be honest, be content',
  },
  {
    slug: '4th-sunday-advent',
    sundayName: '4th Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Luke 1:39-45',
    firstReadingRef: 'Mic 5:1-4a',
    psalmRef: 'Ps 80',
    secondReadingRef: 'Heb 10:5-10',
    oneLineTheme: 'The Visitation — "Blessed are you among women, and blessed is the fruit of your womb"',
  },
  // CHRISTMAS SEASON
  {
    slug: 'holy-family',
    sundayName: 'Holy Family of Jesus, Mary and Joseph',
    season: 'Christmas',
    gospelRef: 'Luke 2:41-52',
    firstReadingRef: '1 Sam 1:20-22, 24-28',
    psalmRef: 'Ps 128',
    secondReadingRef: '1 John 3:1-2, 21-24',
    oneLineTheme: 'Finding Jesus in the Temple — "Did you not know I must be in my Father\'s house?"',
  },
  {
    slug: 'epiphany',
    sundayName: 'Epiphany of the Lord',
    season: 'Christmas',
    gospelRef: 'Matt 2:1-12',
    firstReadingRef: 'Isa 60:1-6',
    psalmRef: 'Ps 72',
    secondReadingRef: 'Eph 3:2-3a, 5-6',
    oneLineTheme: 'The Magi follow the star; nations stream to the light of Christ',
    sameEveryYear: true,
  },
  {
    slug: 'baptism-of-the-lord',
    sundayName: 'Baptism of the Lord',
    season: 'Christmas',
    gospelRef: 'Luke 3:15-16, 21-22',
    firstReadingRef: 'Isa 42:1-4, 6-7',
    psalmRef: 'Ps 104',
    secondReadingRef: 'Titus 2:11-14; 3:4-7',
    oneLineTheme: '"You are my beloved Son; with you I am well pleased" — the Spirit descends like a dove',
  },
  // ORDINARY TIME I
  {
    slug: '2nd-sunday-ordinary-time',
    sundayName: '2nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 2:1-11',
    firstReadingRef: 'Isa 62:1-5',
    psalmRef: 'Ps 96',
    secondReadingRef: '1 Cor 12:4-11',
    oneLineTheme: 'The Wedding at Cana — "Do whatever he tells you" — the first sign',
  },
  {
    slug: '3rd-sunday-ordinary-time',
    sundayName: '3rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 1:1-4; 4:14-21',
    firstReadingRef: 'Neh 8:2-4a, 5-6, 8-10',
    psalmRef: 'Ps 19',
    secondReadingRef: '1 Cor 12:12-30',
    oneLineTheme: '"Today this scripture passage is fulfilled in your hearing" — Jesus in Nazareth',
  },
  {
    slug: '4th-sunday-ordinary-time',
    sundayName: '4th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 4:21-30',
    firstReadingRef: 'Jer 1:4-5, 17-19',
    psalmRef: 'Ps 71',
    secondReadingRef: '1 Cor 12:31–13:13',
    oneLineTheme: 'Rejected at Nazareth — "No prophet is accepted in his own hometown"',
  },
  {
    slug: '5th-sunday-ordinary-time',
    sundayName: '5th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 5:1-11',
    firstReadingRef: 'Isa 6:1-2a, 3-8',
    psalmRef: 'Ps 138',
    secondReadingRef: '1 Cor 15:1-11',
    oneLineTheme: 'The miraculous catch of fish — "Depart from me, Lord, for I am a sinful man"',
  },
  {
    slug: '6th-sunday-ordinary-time',
    sundayName: '6th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 6:17, 20-26',
    firstReadingRef: 'Jer 17:5-8',
    psalmRef: 'Ps 1',
    secondReadingRef: '1 Cor 15:12, 16-20',
    oneLineTheme: 'The Beatitudes (Luke) — "Blessed are the poor; woe to the rich"',
  },
  {
    slug: '7th-sunday-ordinary-time',
    sundayName: '7th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 6:27-38',
    firstReadingRef: '1 Sam 26:2, 7-9, 12-13, 22-23',
    psalmRef: 'Ps 103',
    secondReadingRef: '1 Cor 15:45-49',
    oneLineTheme: '"Love your enemies, do good to those who hate you" — be merciful as your Father',
  },
  {
    slug: '8th-sunday-ordinary-time',
    sundayName: '8th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 6:39-45',
    firstReadingRef: 'Sir 27:4-7',
    psalmRef: 'Ps 92',
    secondReadingRef: '1 Cor 15:54-58',
    oneLineTheme: 'Remove the plank from your own eye — a good tree bears good fruit',
  },
  {
    slug: '9th-sunday-ordinary-time',
    sundayName: '9th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 7:1-10',
    firstReadingRef: '1 Kgs 8:41-43',
    psalmRef: 'Ps 117',
    secondReadingRef: 'Gal 1:1-2, 6-10',
    oneLineTheme: 'The centurion\'s servant — "Say the word and my servant shall be healed"',
  },
  // LENT
  {
    slug: '1st-sunday-lent',
    sundayName: '1st Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Luke 4:1-13',
    firstReadingRef: 'Deut 26:4-10',
    psalmRef: 'Ps 91',
    secondReadingRef: 'Rom 10:8-13',
    oneLineTheme: 'Jesus tempted in the desert — the devil departs "for a time"',
  },
  {
    slug: '2nd-sunday-lent',
    sundayName: '2nd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Luke 9:28b-36',
    firstReadingRef: 'Gen 15:5-12, 17-18',
    psalmRef: 'Ps 27',
    secondReadingRef: 'Phil 3:17–4:1',
    oneLineTheme: 'The Transfiguration — Moses and Elijah speak of the "exodus" Jesus would accomplish',
  },
  {
    slug: '3rd-sunday-lent',
    sundayName: '3rd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Luke 13:1-9',
    firstReadingRef: 'Exod 3:1-8a, 13-15',
    psalmRef: 'Ps 103',
    secondReadingRef: '1 Cor 10:1-6, 10-12',
    oneLineTheme: '"Unless you repent you will perish" — the fig tree given one more year',
  },
  {
    slug: '4th-sunday-lent',
    sundayName: '4th Sunday of Lent (Laetare)',
    season: 'Lent',
    gospelRef: 'Luke 15:1-3, 11-32',
    firstReadingRef: 'Josh 5:9a, 10-12',
    psalmRef: 'Ps 34',
    secondReadingRef: '2 Cor 5:17-21',
    oneLineTheme: 'The Prodigal Son — "He was lost and is found; he was dead and is alive again"',
  },
  {
    slug: '5th-sunday-lent',
    sundayName: '5th Sunday of Lent',
    season: 'Lent',
    gospelRef: 'John 8:1-11',
    firstReadingRef: 'Isa 43:16-21',
    psalmRef: 'Ps 126',
    secondReadingRef: 'Phil 3:8-14',
    oneLineTheme: 'The woman caught in adultery — "Neither do I condemn you; sin no more"',
  },
  {
    slug: 'palm-sunday',
    sundayName: 'Palm Sunday of the Lord\'s Passion',
    season: 'HolyWeek',
    gospelRef: 'Luke 22:14–23:56',
    firstReadingRef: 'Isa 50:4-7',
    psalmRef: 'Ps 22',
    secondReadingRef: 'Phil 2:6-11',
    oneLineTheme: 'The Passion according to Luke — "Father, forgive them; they know not what they do"',
  },
  // EASTER
  {
    slug: 'easter-sunday',
    sundayName: 'Easter Sunday — The Resurrection of the Lord',
    season: 'Easter',
    gospelRef: 'John 20:1-9',
    firstReadingRef: 'Acts 10:34a, 37-43',
    psalmRef: 'Ps 118',
    secondReadingRef: 'Col 3:1-4',
    oneLineTheme: 'The empty tomb — "He had to rise from the dead"',
    sameEveryYear: true,
  },
  {
    slug: '2nd-sunday-easter',
    sundayName: '2nd Sunday of Easter (Divine Mercy Sunday)',
    season: 'Easter',
    gospelRef: 'John 20:19-31',
    firstReadingRef: 'Acts 5:12-16',
    psalmRef: 'Ps 118',
    secondReadingRef: 'Rev 1:9-11a, 12-13, 17-19',
    oneLineTheme: 'Thomas: "My Lord and my God!" — blessed are those who have not seen yet believe',
    sameEveryYear: true,
  },
  {
    slug: '3rd-sunday-easter',
    sundayName: '3rd Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 21:1-19',
    firstReadingRef: 'Acts 5:27b-32, 40b-41',
    psalmRef: 'Ps 30',
    secondReadingRef: 'Rev 5:11-14',
    oneLineTheme: 'The catch of fish; "Do you love me?" — Peter restored three times',
  },
  {
    slug: '4th-sunday-easter',
    sundayName: '4th Sunday of Easter (Good Shepherd Sunday)',
    season: 'Easter',
    gospelRef: 'John 10:27-30',
    firstReadingRef: 'Acts 13:14, 43-52',
    psalmRef: 'Ps 100',
    secondReadingRef: 'Rev 7:9, 14b-17',
    oneLineTheme: '"My sheep hear my voice — no one can take them from my hand"',
  },
  {
    slug: '5th-sunday-easter',
    sundayName: '5th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 13:31-35',
    firstReadingRef: 'Acts 14:21-27',
    psalmRef: 'Ps 145',
    secondReadingRef: 'Rev 21:1-5a',
    oneLineTheme: '"Love one another as I have loved you" — the new commandment',
  },
  {
    slug: '6th-sunday-easter',
    sundayName: '6th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 14:23-29',
    firstReadingRef: 'Acts 15:1-2, 22-29',
    psalmRef: 'Ps 67',
    secondReadingRef: 'Rev 21:10-14, 22-23',
    oneLineTheme: '"Peace I leave you, my peace I give you" — the Holy Spirit will teach you all things',
  },
  {
    slug: 'ascension-of-the-lord',
    sundayName: 'Ascension of the Lord',
    season: 'Easter',
    gospelRef: 'Luke 24:46-53',
    firstReadingRef: 'Acts 1:1-11',
    psalmRef: 'Ps 47',
    secondReadingRef: 'Eph 1:17-23',
    oneLineTheme: '"You are witnesses of these things" — Jesus is taken up; they return with great joy',
  },
  {
    slug: '7th-sunday-easter',
    sundayName: '7th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 17:20-26',
    firstReadingRef: 'Acts 7:55-60',
    psalmRef: 'Ps 97',
    secondReadingRef: 'Rev 22:12-14, 16-17, 20',
    oneLineTheme: 'Jesus prays for all believers — "That they may be one so the world may believe"',
  },
  {
    slug: 'pentecost-sunday',
    sundayName: 'Pentecost Sunday',
    season: 'Easter',
    gospelRef: 'John 20:19-23',
    firstReadingRef: 'Acts 2:1-11',
    psalmRef: 'Ps 104',
    secondReadingRef: '1 Cor 12:3b-7, 12-13',
    oneLineTheme: '"Receive the Holy Spirit — whose sins you forgive are forgiven"',
    sameEveryYear: true,
  },
  // ORDINARY TIME II
  {
    slug: '10th-sunday-ordinary-time',
    sundayName: '10th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 7:11-17',
    firstReadingRef: '1 Kgs 17:17-24',
    psalmRef: 'Ps 30',
    secondReadingRef: 'Gal 1:11-19',
    oneLineTheme: 'Raising the widow\'s son at Nain — "Young man, I say to you, rise!"',
  },
  {
    slug: '11th-sunday-ordinary-time',
    sundayName: '11th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 7:36–8:3',
    firstReadingRef: '2 Sam 12:7-10, 13',
    psalmRef: 'Ps 32',
    secondReadingRef: 'Gal 2:16, 19-21',
    oneLineTheme: 'The sinful woman who weeps at Jesus\'s feet — "Her many sins are forgiven; she loved much"',
  },
  {
    slug: '12th-sunday-ordinary-time',
    sundayName: '12th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 9:18-24',
    firstReadingRef: 'Zech 12:10-11; 13:1',
    psalmRef: 'Ps 63',
    secondReadingRef: 'Gal 3:26-29',
    oneLineTheme: '"Who do you say that I am?" — "Deny yourself, take up your cross daily"',
  },
  {
    slug: '13th-sunday-ordinary-time',
    sundayName: '13th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 9:51-62',
    firstReadingRef: '1 Kgs 19:16b, 19-21',
    psalmRef: 'Ps 16',
    secondReadingRef: 'Gal 5:1, 13-18',
    oneLineTheme: '"No one who looks back is fit for the Kingdom of God" — the cost of following',
  },
  {
    slug: '14th-sunday-ordinary-time',
    sundayName: '14th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 10:1-12, 17-20',
    firstReadingRef: 'Isa 66:10-14c',
    psalmRef: 'Ps 66',
    secondReadingRef: 'Gal 6:14-18',
    oneLineTheme: 'The 72 sent out — "Your names are written in heaven"',
  },
  {
    slug: '15th-sunday-ordinary-time',
    sundayName: '15th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 10:25-37',
    firstReadingRef: 'Deut 30:10-14',
    psalmRef: 'Ps 69',
    secondReadingRef: 'Col 1:15-20',
    oneLineTheme: 'The Good Samaritan — "Who was neighbour to the man who fell to the robbers?"',
  },
  {
    slug: '16th-sunday-ordinary-time',
    sundayName: '16th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 10:38-42',
    firstReadingRef: 'Gen 18:1-10a',
    psalmRef: 'Ps 15',
    secondReadingRef: 'Col 1:24-28',
    oneLineTheme: 'Mary and Martha — "Mary has chosen the better part which will not be taken from her"',
  },
  {
    slug: '17th-sunday-ordinary-time',
    sundayName: '17th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 11:1-13',
    firstReadingRef: 'Gen 18:20-32',
    psalmRef: 'Ps 138',
    secondReadingRef: 'Col 2:12-14',
    oneLineTheme: 'The Our Father; ask, seek, knock — "The Father will give the Holy Spirit to those who ask"',
  },
  {
    slug: '18th-sunday-ordinary-time',
    sundayName: '18th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 12:13-21',
    firstReadingRef: 'Eccl 1:2; 2:21-23',
    psalmRef: 'Ps 90',
    secondReadingRef: 'Col 3:1-5, 9-11',
    oneLineTheme: 'The Rich Fool — "This night your life will be demanded; whose will all this be?"',
  },
  {
    slug: '19th-sunday-ordinary-time',
    sundayName: '19th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 12:32-48',
    firstReadingRef: 'Wis 18:6-9',
    psalmRef: 'Ps 33',
    secondReadingRef: 'Heb 11:1-2, 8-19',
    oneLineTheme: '"Do not be afraid, little flock" — be ready, lamps lit; faithful stewards',
  },
  {
    slug: '20th-sunday-ordinary-time',
    sundayName: '20th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 12:49-53',
    firstReadingRef: 'Jer 38:4-6, 8-10',
    psalmRef: 'Ps 40',
    secondReadingRef: 'Heb 12:1-4',
    oneLineTheme: '"I have come to bring fire on the earth" — not peace but division',
  },
  {
    slug: '21st-sunday-ordinary-time',
    sundayName: '21st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 13:22-30',
    firstReadingRef: 'Isa 66:18-21',
    psalmRef: 'Ps 117',
    secondReadingRef: 'Heb 12:5-7, 11-13',
    oneLineTheme: '"Strive to enter through the narrow gate" — people from all nations at the feast',
  },
  {
    slug: '22nd-sunday-ordinary-time',
    sundayName: '22nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 14:1, 7-14',
    firstReadingRef: 'Sir 3:17-18, 20, 28-29',
    psalmRef: 'Ps 68',
    secondReadingRef: 'Heb 12:18-19, 22-24a',
    oneLineTheme: 'Take the lowest place; invite the poor and lame — "You will be repaid at the resurrection"',
  },
  {
    slug: '23rd-sunday-ordinary-time',
    sundayName: '23rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 14:25-33',
    firstReadingRef: 'Wis 9:13-18b',
    psalmRef: 'Ps 90',
    secondReadingRef: 'Phlm 9-10, 12-17',
    oneLineTheme: 'Counting the cost — "Whoever does not renounce all his possessions cannot be my disciple"',
  },
  {
    slug: '24th-sunday-ordinary-time',
    sundayName: '24th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 15:1-32',
    firstReadingRef: 'Exod 32:7-11, 13-14',
    psalmRef: 'Ps 51',
    secondReadingRef: '1 Tim 1:12-17',
    oneLineTheme: 'Lost sheep, lost coin, Prodigal Son — "There is more joy in heaven over one sinner who repents"',
  },
  {
    slug: '25th-sunday-ordinary-time',
    sundayName: '25th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 16:1-13',
    firstReadingRef: 'Amos 8:4-7',
    psalmRef: 'Ps 113',
    secondReadingRef: '1 Tim 2:1-8',
    oneLineTheme: 'The Dishonest Steward — "You cannot serve both God and mammon"',
  },
  {
    slug: '26th-sunday-ordinary-time',
    sundayName: '26th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 16:19-31',
    firstReadingRef: 'Amos 6:1a, 4-7',
    psalmRef: 'Ps 146',
    secondReadingRef: '1 Tim 6:11-16',
    oneLineTheme: 'The Rich Man and Lazarus — a great chasm fixed; "They have Moses and the prophets"',
  },
  {
    slug: '27th-sunday-ordinary-time',
    sundayName: '27th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 17:5-10',
    firstReadingRef: 'Hab 1:2-3; 2:2-4',
    psalmRef: 'Ps 95',
    secondReadingRef: '2 Tim 1:6-8, 13-14',
    oneLineTheme: '"Increase our faith" — faith like a mustard seed; "We are unprofitable servants"',
  },
  {
    slug: '28th-sunday-ordinary-time',
    sundayName: '28th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 17:11-19',
    firstReadingRef: '2 Kgs 5:14-17',
    psalmRef: 'Ps 98',
    secondReadingRef: '2 Tim 2:8-13',
    oneLineTheme: 'Ten lepers healed; only the Samaritan returns — "Your faith has saved you"',
  },
  {
    slug: '29th-sunday-ordinary-time',
    sundayName: '29th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 18:1-8',
    firstReadingRef: 'Exod 17:8-13',
    psalmRef: 'Ps 121',
    secondReadingRef: '2 Tim 3:14–4:2',
    oneLineTheme: 'The Persistent Widow — "Will not God secure justice for his chosen who cry out day and night?"',
  },
  {
    slug: '30th-sunday-ordinary-time',
    sundayName: '30th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 18:9-14',
    firstReadingRef: 'Sir 35:12-14, 16-18',
    psalmRef: 'Ps 34',
    secondReadingRef: '2 Tim 4:6-8, 16-18',
    oneLineTheme: 'Pharisee and tax collector — "Whoever humbles himself will be exalted"',
  },
  {
    slug: '31st-sunday-ordinary-time',
    sundayName: '31st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 19:1-10',
    firstReadingRef: 'Wis 11:22–12:2',
    psalmRef: 'Ps 145',
    secondReadingRef: '2 Thess 1:11–2:2',
    oneLineTheme: 'Zacchaeus: "Today salvation has come to this house — the Son of Man came to seek the lost"',
  },
  {
    slug: '32nd-sunday-ordinary-time',
    sundayName: '32nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 20:27-38',
    firstReadingRef: '2 Macc 7:1-2, 9-14',
    psalmRef: 'Ps 17',
    secondReadingRef: '2 Thess 2:16–3:5',
    oneLineTheme: 'The Resurrection — "God is not of the dead but of the living; all are alive to him"',
  },
  {
    slug: '33rd-sunday-ordinary-time',
    sundayName: '33rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 21:5-19',
    firstReadingRef: 'Mal 3:19-20a',
    psalmRef: 'Ps 98',
    secondReadingRef: '2 Thess 3:7-12',
    oneLineTheme: 'Signs of the end — "By your perseverance you will secure your lives"',
  },
  {
    slug: 'christ-the-king',
    sundayName: '34th Sunday — Our Lord Jesus Christ, King of the Universe',
    season: 'OrdinaryTime',
    gospelRef: 'Luke 23:35-43',
    firstReadingRef: '2 Sam 5:1-3',
    psalmRef: 'Ps 122',
    secondReadingRef: 'Col 1:12-20',
    oneLineTheme: '"Today you will be with me in paradise" — the repentant thief and the merciful King',
  },
]

export default yearC
