import type { SundayEntry } from '../types'

// Year A — Gospel of Matthew (Advent 2025 – Christ the King 2026)
// Sources: USCCB Lectionary for Mass, NABRE edition
const yearA: SundayEntry[] = [
  // ADVENT
  {
    slug: '1st-sunday-advent',
    sundayName: '1st Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Matt 24:37-44',
    firstReadingRef: 'Isa 2:1-5',
    psalmRef: 'Ps 122',
    secondReadingRef: 'Rom 13:11-14',
    oneLineTheme: 'Stay awake — the Son of Man comes like a thief in the night',
  },
  {
    slug: '2nd-sunday-advent',
    sundayName: '2nd Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Matt 3:1-12',
    firstReadingRef: 'Isa 11:1-10',
    psalmRef: 'Ps 72',
    secondReadingRef: 'Rom 15:4-9',
    oneLineTheme: 'John the Baptist: "Prepare the way of the Lord; produce good fruit"',
  },
  {
    slug: '3rd-sunday-advent',
    sundayName: '3rd Sunday of Advent (Gaudete)',
    season: 'Advent',
    gospelRef: 'Matt 11:2-11',
    firstReadingRef: 'Isa 35:1-6a, 10',
    psalmRef: 'Ps 146',
    secondReadingRef: 'Jas 5:7-10',
    oneLineTheme: '"Are you the one who is to come?" — the blind see, the lame walk',
  },
  {
    slug: '4th-sunday-advent',
    sundayName: '4th Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Matt 1:18-24',
    firstReadingRef: 'Isa 7:10-14',
    psalmRef: 'Ps 24',
    secondReadingRef: 'Rom 1:1-7',
    oneLineTheme: 'Joseph\'s dream: "Emmanuel — God is with us"',
  },
  // CHRISTMAS SEASON
  {
    slug: 'holy-family',
    sundayName: 'Holy Family of Jesus, Mary and Joseph',
    season: 'Christmas',
    gospelRef: 'Matt 2:13-15, 19-23',
    firstReadingRef: 'Sir 3:2-6, 12-14',
    psalmRef: 'Ps 128',
    secondReadingRef: 'Col 3:12-21',
    oneLineTheme: 'Flight into Egypt — the Holy Family trusts God through exile and return',
  },
  {
    slug: 'epiphany',
    sundayName: 'Epiphany of the Lord',
    season: 'Christmas',
    gospelRef: 'Matt 2:1-12',
    firstReadingRef: 'Isa 60:1-6',
    psalmRef: 'Ps 72',
    secondReadingRef: 'Eph 3:2-3a, 5-6',
    oneLineTheme: 'The Magi follow the star; nations stream to the light of Christ',
    sameEveryYear: true,
  },
  {
    slug: 'baptism-of-the-lord',
    sundayName: 'Baptism of the Lord',
    season: 'Christmas',
    gospelRef: 'Matt 3:13-17',
    firstReadingRef: 'Isa 42:1-4, 6-7',
    psalmRef: 'Ps 29',
    secondReadingRef: 'Acts 10:34-38',
    oneLineTheme: '"This is my beloved Son" — Jesus revealed at the Jordan',
  },
  // ORDINARY TIME I
  {
    slug: '2nd-sunday-ordinary-time',
    sundayName: '2nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 1:29-34',
    firstReadingRef: 'Isa 49:3, 5-6',
    psalmRef: 'Ps 40',
    secondReadingRef: '1 Cor 1:1-3',
    oneLineTheme: '"Behold the Lamb of God who takes away the sin of the world"',
  },
  {
    slug: '3rd-sunday-ordinary-time',
    sundayName: '3rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 4:12-23',
    firstReadingRef: 'Isa 8:23–9:3',
    psalmRef: 'Ps 27',
    secondReadingRef: '1 Cor 1:10-13, 17',
    oneLineTheme: '"Follow me and I will make you fishers of men" — the call of the disciples',
  },
  {
    slug: '4th-sunday-ordinary-time',
    sundayName: '4th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 5:1-12a',
    firstReadingRef: 'Zeph 2:3; 3:12-13',
    psalmRef: 'Ps 146',
    secondReadingRef: '1 Cor 1:26-31',
    oneLineTheme: 'The Beatitudes — the upside-down logic of the Kingdom of Heaven',
  },
  {
    slug: '5th-sunday-ordinary-time',
    sundayName: '5th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 5:13-16',
    firstReadingRef: 'Isa 58:7-10',
    psalmRef: 'Ps 112',
    secondReadingRef: '1 Cor 2:1-5',
    oneLineTheme: 'You are the salt of the earth and the light of the world',
  },
  {
    slug: '6th-sunday-ordinary-time',
    sundayName: '6th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 5:17-37',
    firstReadingRef: 'Sir 15:15-20',
    psalmRef: 'Ps 119',
    secondReadingRef: '1 Cor 2:6-10',
    oneLineTheme: '"You have heard it said… but I say to you" — Jesus fulfils and deepens the Law',
  },
  {
    slug: '7th-sunday-ordinary-time',
    sundayName: '7th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 5:38-48',
    firstReadingRef: 'Lev 19:1-2, 17-18',
    psalmRef: 'Ps 103',
    secondReadingRef: '1 Cor 3:16-23',
    oneLineTheme: 'Love your enemies; be perfect as your heavenly Father is perfect',
  },
  {
    slug: '8th-sunday-ordinary-time',
    sundayName: '8th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 6:24-34',
    firstReadingRef: 'Isa 49:14-15',
    psalmRef: 'Ps 62',
    secondReadingRef: '1 Cor 4:1-5',
    oneLineTheme: 'No one can serve two masters — seek first the Kingdom of God',
  },
  {
    slug: '9th-sunday-ordinary-time',
    sundayName: '9th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 7:21-27',
    firstReadingRef: 'Deut 11:18, 26-28',
    psalmRef: 'Ps 31',
    secondReadingRef: 'Rom 3:21-25, 28',
    oneLineTheme: 'Build on rock, not sand — hearing the Lord\'s words and acting on them',
  },
  // LENT
  {
    slug: '1st-sunday-lent',
    sundayName: '1st Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Matt 4:1-11',
    firstReadingRef: 'Gen 2:7-9; 3:1-7',
    psalmRef: 'Ps 51',
    secondReadingRef: 'Rom 5:12-19',
    oneLineTheme: 'Jesus tempted in the desert — where Adam fell, Christ stands firm',
  },
  {
    slug: '2nd-sunday-lent',
    sundayName: '2nd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Matt 17:1-9',
    firstReadingRef: 'Gen 12:1-4a',
    psalmRef: 'Ps 33',
    secondReadingRef: '2 Tim 1:8b-10',
    oneLineTheme: 'The Transfiguration — Jesus\' face shines like the sun on the holy mountain',
  },
  {
    slug: '3rd-sunday-lent',
    sundayName: '3rd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'John 4:5-42',
    firstReadingRef: 'Exod 17:3-7',
    psalmRef: 'Ps 95',
    secondReadingRef: 'Rom 5:1-2, 5-8',
    oneLineTheme: 'The Samaritan woman at the well — "The water I give becomes an eternal spring"',
  },
  {
    slug: '4th-sunday-lent',
    sundayName: '4th Sunday of Lent (Laetare)',
    season: 'Lent',
    gospelRef: 'John 9:1-41',
    firstReadingRef: '1 Sam 16:1b, 6-7, 10-13a',
    psalmRef: 'Ps 23',
    secondReadingRef: 'Eph 5:8-14',
    oneLineTheme: 'The man born blind: "I was blind, now I see" — light vs. wilful darkness',
  },
  {
    slug: '5th-sunday-lent',
    sundayName: '5th Sunday of Lent',
    season: 'Lent',
    gospelRef: 'John 11:1-45',
    firstReadingRef: 'Ezek 37:12-14',
    psalmRef: 'Ps 130',
    secondReadingRef: 'Rom 8:8-11',
    oneLineTheme: 'The raising of Lazarus — "I am the resurrection and the life"',
  },
  {
    slug: 'palm-sunday',
    sundayName: 'Palm Sunday of the Lord\'s Passion',
    season: 'HolyWeek',
    gospelRef: 'Matt 26:14–27:66',
    firstReadingRef: 'Isa 50:4-7',
    psalmRef: 'Ps 22',
    secondReadingRef: 'Phil 2:6-11',
    oneLineTheme: 'The Passion according to Matthew — the King enters Jerusalem and gives his life',
  },
  // EASTER
  {
    slug: 'easter-sunday',
    sundayName: 'Easter Sunday — The Resurrection of the Lord',
    season: 'Easter',
    gospelRef: 'John 20:1-9',
    firstReadingRef: 'Acts 10:34a, 37-43',
    psalmRef: 'Ps 118',
    secondReadingRef: 'Col 3:1-4',
    oneLineTheme: 'The empty tomb — "He had to rise from the dead"',
    sameEveryYear: true,
  },
  {
    slug: '2nd-sunday-easter',
    sundayName: '2nd Sunday of Easter (Divine Mercy Sunday)',
    season: 'Easter',
    gospelRef: 'John 20:19-31',
    firstReadingRef: 'Acts 2:42-47',
    psalmRef: 'Ps 118',
    secondReadingRef: '1 Pet 1:3-9',
    oneLineTheme: 'Thomas: "My Lord and my God!" — blessed are those who have not seen yet believe',
    sameEveryYear: true,
  },
  {
    slug: '3rd-sunday-easter',
    sundayName: '3rd Sunday of Easter',
    season: 'Easter',
    gospelRef: 'Luke 24:13-35',
    firstReadingRef: 'Acts 2:14, 22-33',
    psalmRef: 'Ps 16',
    secondReadingRef: '1 Pet 1:17-21',
    oneLineTheme: 'The Road to Emmaus — hearts burning as he opened the Scriptures',
  },
  {
    slug: '4th-sunday-easter',
    sundayName: '4th Sunday of Easter (Good Shepherd Sunday)',
    season: 'Easter',
    gospelRef: 'John 10:1-10',
    firstReadingRef: 'Acts 2:14a, 36-41',
    psalmRef: 'Ps 23',
    secondReadingRef: '1 Pet 2:20b-25',
    oneLineTheme: '"I am the gate — whoever enters through me will be saved and find pasture"',
  },
  {
    slug: '5th-sunday-easter',
    sundayName: '5th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 14:1-12',
    firstReadingRef: 'Acts 6:1-7',
    psalmRef: 'Ps 33',
    secondReadingRef: '1 Pet 2:4-9',
    oneLineTheme: '"I am the way, the truth, and the life" — Thomas asks the way; Philip asks the Father',
  },
  {
    slug: '6th-sunday-easter',
    sundayName: '6th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 14:15-21',
    firstReadingRef: 'Acts 8:5-8, 14-17',
    psalmRef: 'Ps 66',
    secondReadingRef: '1 Pet 3:15-18',
    oneLineTheme: '"I will ask the Father and he will give you another Advocate to be with you always"',
  },
  {
    slug: 'ascension-of-the-lord',
    sundayName: 'Ascension of the Lord',
    season: 'Easter',
    gospelRef: 'Matt 28:16-20',
    firstReadingRef: 'Acts 1:1-11',
    psalmRef: 'Ps 47',
    secondReadingRef: 'Eph 1:17-23',
    oneLineTheme: '"Go and make disciples of all nations" — the Great Commission',
  },
  {
    slug: '7th-sunday-easter',
    sundayName: '7th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 17:1-11a',
    firstReadingRef: 'Acts 1:12-14',
    psalmRef: 'Ps 27',
    secondReadingRef: '1 Pet 4:13-16',
    oneLineTheme: 'Jesus prays for unity: "That they may all be one as we are one"',
    hasCommentary: true,
  },
  {
    slug: 'pentecost-sunday',
    sundayName: 'Pentecost Sunday',
    season: 'Easter',
    gospelRef: 'John 20:19-23',
    firstReadingRef: 'Acts 2:1-11',
    psalmRef: 'Ps 104',
    secondReadingRef: '1 Cor 12:3b-7, 12-13',
    oneLineTheme: '"Receive the Holy Spirit — whose sins you forgive are forgiven"',
    sameEveryYear: true,
  },
  // ORDINARY TIME II (after Pentecost)
  {
    slug: '10th-sunday-ordinary-time',
    sundayName: '10th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 9:9-13',
    firstReadingRef: 'Hos 6:3-6',
    psalmRef: 'Ps 50',
    secondReadingRef: 'Rom 4:18-25',
    oneLineTheme: 'The call of Matthew: "It is mercy I desire, not sacrifice"',
  },
  {
    slug: '11th-sunday-ordinary-time',
    sundayName: '11th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 9:36–10:8',
    firstReadingRef: 'Exod 19:2-6a',
    psalmRef: 'Ps 100',
    secondReadingRef: 'Rom 5:6-11',
    oneLineTheme: '"The harvest is abundant but the laborers are few" — sending out the Twelve',
  },
  {
    slug: '12th-sunday-ordinary-time',
    sundayName: '12th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 10:26-33',
    firstReadingRef: 'Jer 20:10-13',
    psalmRef: 'Ps 69',
    secondReadingRef: 'Rom 5:12-15',
    oneLineTheme: 'Fear not those who kill the body — "Every hair on your head is counted"',
  },
  {
    slug: '13th-sunday-ordinary-time',
    sundayName: '13th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 10:37-42',
    firstReadingRef: '2 Kgs 4:8-11, 14-16a',
    psalmRef: 'Ps 89',
    secondReadingRef: 'Rom 6:3-4, 8-11',
    oneLineTheme: '"Whoever receives you receives me" — giving even a cup of cold water',
  },
  {
    slug: '14th-sunday-ordinary-time',
    sundayName: '14th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 11:25-30',
    firstReadingRef: 'Zech 9:9-10',
    psalmRef: 'Ps 145',
    secondReadingRef: 'Rom 8:9, 11-13',
    oneLineTheme: '"Come to me, all who are weary — my yoke is easy and my burden light"',
  },
  {
    slug: '15th-sunday-ordinary-time',
    sundayName: '15th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 13:1-23',
    firstReadingRef: 'Isa 55:10-11',
    psalmRef: 'Ps 65',
    secondReadingRef: 'Rom 8:18-23',
    oneLineTheme: 'Parable of the Sower — the Word bears fruit in good soil',
  },
  {
    slug: '16th-sunday-ordinary-time',
    sundayName: '16th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 13:24-43',
    firstReadingRef: 'Wis 12:13, 16-19',
    psalmRef: 'Ps 86',
    secondReadingRef: 'Rom 8:26-27',
    oneLineTheme: 'Wheat and weeds — God\'s patience with the Church until the harvest',
  },
  {
    slug: '17th-sunday-ordinary-time',
    sundayName: '17th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 13:44-52',
    firstReadingRef: '1 Kgs 3:5, 7-12',
    psalmRef: 'Ps 119',
    secondReadingRef: 'Rom 8:28-30',
    oneLineTheme: 'Hidden treasure and pearl of great price — the Kingdom worth everything',
  },
  {
    slug: '18th-sunday-ordinary-time',
    sundayName: '18th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 14:13-21',
    firstReadingRef: 'Isa 55:1-3',
    psalmRef: 'Ps 145',
    secondReadingRef: 'Rom 8:35, 37-39',
    oneLineTheme: 'Feeding of the 5,000 — Jesus feeds the crowd with five loaves and two fish',
  },
  {
    slug: '19th-sunday-ordinary-time',
    sundayName: '19th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 14:22-33',
    firstReadingRef: '1 Kgs 19:9a, 11-13a',
    psalmRef: 'Ps 85',
    secondReadingRef: 'Rom 9:1-5',
    oneLineTheme: 'Jesus walks on water; Peter sinks — "Lord, save me; why did you doubt?"',
  },
  {
    slug: '20th-sunday-ordinary-time',
    sundayName: '20th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 15:21-28',
    firstReadingRef: 'Isa 56:1, 6-7',
    psalmRef: 'Ps 67',
    secondReadingRef: 'Rom 11:13-15, 29-32',
    oneLineTheme: 'The Canaanite woman: "Great is your faith! Let it be as you wish"',
  },
  {
    slug: '21st-sunday-ordinary-time',
    sundayName: '21st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 16:13-20',
    firstReadingRef: 'Isa 22:19-23',
    psalmRef: 'Ps 138',
    secondReadingRef: 'Rom 11:33-36',
    oneLineTheme: '"You are Peter and on this rock I will build my Church" — the keys of the kingdom',
  },
  {
    slug: '22nd-sunday-ordinary-time',
    sundayName: '22nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 16:21-27',
    firstReadingRef: 'Jer 20:7-9',
    psalmRef: 'Ps 63',
    secondReadingRef: 'Rom 12:1-2',
    oneLineTheme: '"Take up your cross and follow me — whoever loses their life will find it"',
  },
  {
    slug: '23rd-sunday-ordinary-time',
    sundayName: '23rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 18:15-20',
    firstReadingRef: 'Ezek 33:7-9',
    psalmRef: 'Ps 95',
    secondReadingRef: 'Rom 13:8-10',
    oneLineTheme: 'Fraternal correction — "Where two or three are gathered in my name, I am there"',
  },
  {
    slug: '24th-sunday-ordinary-time',
    sundayName: '24th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 18:21-35',
    firstReadingRef: 'Sir 27:30–28:7',
    psalmRef: 'Ps 103',
    secondReadingRef: 'Rom 14:7-9',
    oneLineTheme: 'The Unforgiving Servant — "Forgive your brother not seven but seventy-seven times"',
  },
  {
    slug: '25th-sunday-ordinary-time',
    sundayName: '25th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 20:1-16a',
    firstReadingRef: 'Isa 55:6-9',
    psalmRef: 'Ps 145',
    secondReadingRef: 'Phil 1:20c-24, 27a',
    oneLineTheme: 'Workers in the vineyard — "Are you envious because I am generous?"',
  },
  {
    slug: '26th-sunday-ordinary-time',
    sundayName: '26th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 21:28-32',
    firstReadingRef: 'Ezek 18:25-28',
    psalmRef: 'Ps 25',
    secondReadingRef: 'Phil 2:1-11',
    oneLineTheme: 'The Two Sons — actions speak louder than words; tax collectors enter before priests',
  },
  {
    slug: '27th-sunday-ordinary-time',
    sundayName: '27th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 21:33-43',
    firstReadingRef: 'Isa 5:1-7',
    psalmRef: 'Ps 80',
    secondReadingRef: 'Phil 4:6-9',
    oneLineTheme: 'The Wicked Tenants — the Kingdom will be given to those who produce its fruit',
  },
  {
    slug: '28th-sunday-ordinary-time',
    sundayName: '28th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 22:1-14',
    firstReadingRef: 'Isa 25:6-10a',
    psalmRef: 'Ps 23',
    secondReadingRef: 'Phil 4:12-14, 19-20',
    oneLineTheme: 'The Wedding Banquet — "Many are invited but few are chosen"',
  },
  {
    slug: '29th-sunday-ordinary-time',
    sundayName: '29th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 22:15-21',
    firstReadingRef: 'Isa 45:1, 4-6',
    psalmRef: 'Ps 96',
    secondReadingRef: '1 Thess 1:1-5b',
    oneLineTheme: '"Repay to Caesar what is Caesar\'s and to God what is God\'s"',
  },
  {
    slug: '30th-sunday-ordinary-time',
    sundayName: '30th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 22:34-40',
    firstReadingRef: 'Exod 22:20-26',
    psalmRef: 'Ps 18',
    secondReadingRef: '1 Thess 1:5c-10',
    oneLineTheme: 'The Greatest Commandment — love God with all your heart, love your neighbour',
  },
  {
    slug: '31st-sunday-ordinary-time',
    sundayName: '31st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 23:1-12',
    firstReadingRef: 'Mal 1:14b–2:2b, 8-10',
    psalmRef: 'Ps 131',
    secondReadingRef: '1 Thess 2:7b-9, 13',
    oneLineTheme: '"Do not follow their example" — humble service, not titles and honour',
  },
  {
    slug: '32nd-sunday-ordinary-time',
    sundayName: '32nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 25:1-13',
    firstReadingRef: 'Wis 6:12-16',
    psalmRef: 'Ps 63',
    secondReadingRef: '1 Thess 4:13-18',
    oneLineTheme: 'The Ten Virgins — keep your lamp burning; stay awake for the Bridegroom',
  },
  {
    slug: '33rd-sunday-ordinary-time',
    sundayName: '33rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 25:14-30',
    firstReadingRef: 'Prov 31:10-13, 19-20, 30-31',
    psalmRef: 'Ps 128',
    secondReadingRef: '1 Thess 5:1-6',
    oneLineTheme: 'The Talents — use the gifts entrusted to you; do not bury them out of fear',
  },
  {
    slug: 'christ-the-king',
    sundayName: '34th Sunday — Our Lord Jesus Christ, King of the Universe',
    season: 'OrdinaryTime',
    gospelRef: 'Matt 25:31-46',
    firstReadingRef: 'Ezek 34:11-12, 15-17',
    psalmRef: 'Ps 23',
    secondReadingRef: '1 Cor 15:20-26, 28',
    oneLineTheme: '"Whatever you did to the least of these, you did to me" — the Last Judgement',
  },
]

export default yearA
