import type { SundayEntry } from '../types'

// Year B — Gospel of Mark (with John 6 in summer) — Advent 2026 – Christ the King 2027
// Sources: USCCB Lectionary for Mass, NABRE edition
const yearB: SundayEntry[] = [
  // ADVENT
  {
    slug: '1st-sunday-advent',
    sundayName: '1st Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Mark 13:33-37',
    firstReadingRef: 'Isa 63:16b-17, 19b; 64:2-7',
    psalmRef: 'Ps 80',
    secondReadingRef: '1 Cor 1:3-9',
    oneLineTheme: '"Be watchful! Be alert!" — the Son of Man comes; you do not know the hour',
  },
  {
    slug: '2nd-sunday-advent',
    sundayName: '2nd Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Mark 1:1-8',
    firstReadingRef: 'Isa 40:1-5, 9-11',
    psalmRef: 'Ps 85',
    secondReadingRef: '2 Pet 3:8-14',
    oneLineTheme: '"Prepare the way of the Lord; make straight his paths" — John baptises in the desert',
  },
  {
    slug: '3rd-sunday-advent',
    sundayName: '3rd Sunday of Advent (Gaudete)',
    season: 'Advent',
    gospelRef: 'John 1:6-8, 19-28',
    firstReadingRef: 'Isa 61:1-2a, 10-11',
    psalmRef: 'Luke 1:46-48, 49-50, 53-54',
    secondReadingRef: '1 Thess 5:16-24',
    oneLineTheme: 'John: "I am not the Christ" — a witness to the light, not the light itself',
  },
  {
    slug: '4th-sunday-advent',
    sundayName: '4th Sunday of Advent',
    season: 'Advent',
    gospelRef: 'Luke 1:26-38',
    firstReadingRef: '2 Sam 7:1-5, 8b-12, 14a, 16',
    psalmRef: 'Ps 89',
    secondReadingRef: 'Rom 16:25-27',
    oneLineTheme: 'The Annunciation — "Let it be done to me according to your word"',
  },
  // CHRISTMAS SEASON
  {
    slug: 'holy-family',
    sundayName: 'Holy Family of Jesus, Mary and Joseph',
    season: 'Christmas',
    gospelRef: 'Luke 2:22-40',
    firstReadingRef: 'Sir 3:2-6, 12-14',
    psalmRef: 'Ps 105',
    secondReadingRef: 'Col 3:12-21',
    oneLineTheme: 'The Presentation — Simeon\'s canticle; Jesus grows in wisdom and grace',
  },
  {
    slug: 'epiphany',
    sundayName: 'Epiphany of the Lord',
    season: 'Christmas',
    gospelRef: 'Matt 2:1-12',
    firstReadingRef: 'Isa 60:1-6',
    psalmRef: 'Ps 72',
    secondReadingRef: 'Eph 3:2-3a, 5-6',
    oneLineTheme: 'The Magi follow the star; nations stream to the light of Christ',
    sameEveryYear: true,
  },
  {
    slug: 'baptism-of-the-lord',
    sundayName: 'Baptism of the Lord',
    season: 'Christmas',
    gospelRef: 'Mark 1:7-11',
    firstReadingRef: 'Isa 42:1-4, 6-7',
    psalmRef: 'Ps 29',
    secondReadingRef: 'Acts 10:34-38',
    oneLineTheme: '"You are my beloved Son; with you I am well pleased"',
  },
  // ORDINARY TIME I
  {
    slug: '2nd-sunday-ordinary-time',
    sundayName: '2nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 1:35-42',
    firstReadingRef: '1 Sam 3:3b-10, 19',
    psalmRef: 'Ps 40',
    secondReadingRef: '1 Cor 6:13c-15a, 17-20',
    oneLineTheme: '"What are you looking for?" — Andrew and the first disciples follow Jesus',
  },
  {
    slug: '3rd-sunday-ordinary-time',
    sundayName: '3rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 1:14-20',
    firstReadingRef: 'Jonah 3:1-5, 10',
    psalmRef: 'Ps 25',
    secondReadingRef: '1 Cor 7:29-31',
    oneLineTheme: '"The Kingdom of God is at hand — repent and believe the Gospel"',
  },
  {
    slug: '4th-sunday-ordinary-time',
    sundayName: '4th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 1:21-28',
    firstReadingRef: 'Deut 18:15-20',
    psalmRef: 'Ps 95',
    secondReadingRef: '1 Cor 7:32-35',
    oneLineTheme: 'Jesus teaches with authority and drives out an unclean spirit in Capernaum',
  },
  {
    slug: '5th-sunday-ordinary-time',
    sundayName: '5th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 1:29-39',
    firstReadingRef: 'Job 7:1-4, 6-7',
    psalmRef: 'Ps 147',
    secondReadingRef: '1 Cor 9:16-19, 22-23',
    oneLineTheme: 'Healing Peter\'s mother-in-law; Jesus rises before dawn to pray and preach',
  },
  {
    slug: '6th-sunday-ordinary-time',
    sundayName: '6th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 1:40-45',
    firstReadingRef: 'Lev 13:1-2, 44-46',
    psalmRef: 'Ps 32',
    secondReadingRef: '1 Cor 10:31–11:1',
    oneLineTheme: '"If you wish, you can make me clean" — Jesus touches and heals the leper',
  },
  {
    slug: '7th-sunday-ordinary-time',
    sundayName: '7th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 2:1-12',
    firstReadingRef: 'Isa 43:18-19, 21-22, 24b-25',
    psalmRef: 'Ps 41',
    secondReadingRef: '2 Cor 1:18-22',
    oneLineTheme: 'The paralytic lowered through the roof — "Your sins are forgiven; rise and walk"',
  },
  {
    slug: '8th-sunday-ordinary-time',
    sundayName: '8th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 2:18-22',
    firstReadingRef: 'Hos 2:16b, 17b, 21-22',
    psalmRef: 'Ps 103',
    secondReadingRef: '2 Cor 3:1b-6',
    oneLineTheme: 'New wine in new wineskins — the Kingdom of God cannot be contained by old forms',
  },
  {
    slug: '9th-sunday-ordinary-time',
    sundayName: '9th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 2:23–3:6',
    firstReadingRef: 'Deut 5:12-15',
    psalmRef: 'Ps 81',
    secondReadingRef: '2 Cor 4:6-11',
    oneLineTheme: '"The Sabbath was made for man, not man for the Sabbath" — Lord of the Sabbath',
  },
  // LENT
  {
    slug: '1st-sunday-lent',
    sundayName: '1st Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Mark 1:12-15',
    firstReadingRef: 'Gen 9:8-15',
    psalmRef: 'Ps 25',
    secondReadingRef: '1 Pet 3:18-22',
    oneLineTheme: 'Jesus in the desert with wild beasts and angels — "Repent and believe the Gospel"',
  },
  {
    slug: '2nd-sunday-lent',
    sundayName: '2nd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'Mark 9:2-10',
    firstReadingRef: 'Gen 22:1-2, 9a, 10-13, 15-18',
    psalmRef: 'Ps 116',
    secondReadingRef: 'Rom 8:31b-34',
    oneLineTheme: 'The Transfiguration — "This is my beloved Son; listen to him"',
  },
  {
    slug: '3rd-sunday-lent',
    sundayName: '3rd Sunday of Lent',
    season: 'Lent',
    gospelRef: 'John 2:13-25',
    firstReadingRef: 'Exod 20:1-17',
    psalmRef: 'Ps 19',
    secondReadingRef: '1 Cor 1:22-25',
    oneLineTheme: 'Jesus cleanses the Temple — "Destroy this temple and in three days I will raise it"',
  },
  {
    slug: '4th-sunday-lent',
    sundayName: '4th Sunday of Lent (Laetare)',
    season: 'Lent',
    gospelRef: 'John 3:14-21',
    firstReadingRef: '2 Chr 36:14-16, 19-23',
    psalmRef: 'Ps 137',
    secondReadingRef: 'Eph 2:4-10',
    oneLineTheme: '"God so loved the world that he gave his only Son" — John 3:16',
  },
  {
    slug: '5th-sunday-lent',
    sundayName: '5th Sunday of Lent',
    season: 'Lent',
    gospelRef: 'John 12:20-33',
    firstReadingRef: 'Jer 31:31-34',
    psalmRef: 'Ps 51',
    secondReadingRef: 'Heb 5:7-9',
    oneLineTheme: '"Unless a grain of wheat falls and dies, it remains alone" — the hour has come',
  },
  {
    slug: 'palm-sunday',
    sundayName: 'Palm Sunday of the Lord\'s Passion',
    season: 'HolyWeek',
    gospelRef: 'Mark 14:1–15:47',
    firstReadingRef: 'Isa 50:4-7',
    psalmRef: 'Ps 22',
    secondReadingRef: 'Phil 2:6-11',
    oneLineTheme: 'The Passion according to Mark — Jesus the Servant-Messiah gives his life',
  },
  // EASTER
  {
    slug: 'easter-sunday',
    sundayName: 'Easter Sunday — The Resurrection of the Lord',
    season: 'Easter',
    gospelRef: 'John 20:1-9',
    firstReadingRef: 'Acts 10:34a, 37-43',
    psalmRef: 'Ps 118',
    secondReadingRef: 'Col 3:1-4',
    oneLineTheme: 'The empty tomb — "He had to rise from the dead"',
    sameEveryYear: true,
  },
  {
    slug: '2nd-sunday-easter',
    sundayName: '2nd Sunday of Easter (Divine Mercy Sunday)',
    season: 'Easter',
    gospelRef: 'John 20:19-31',
    firstReadingRef: 'Acts 4:32-35',
    psalmRef: 'Ps 118',
    secondReadingRef: '1 John 5:1-6',
    oneLineTheme: 'Thomas: "My Lord and my God!" — blessed are those who have not seen yet believe',
    sameEveryYear: true,
  },
  {
    slug: '3rd-sunday-easter',
    sundayName: '3rd Sunday of Easter',
    season: 'Easter',
    gospelRef: 'Luke 24:35-48',
    firstReadingRef: 'Acts 3:13-15, 17-19',
    psalmRef: 'Ps 4',
    secondReadingRef: '1 John 2:1-5a',
    oneLineTheme: 'Jesus appears in Jerusalem — "Touch me; a ghost does not have flesh and bone"',
  },
  {
    slug: '4th-sunday-easter',
    sundayName: '4th Sunday of Easter (Good Shepherd Sunday)',
    season: 'Easter',
    gospelRef: 'John 10:11-18',
    firstReadingRef: 'Acts 4:8-12',
    psalmRef: 'Ps 118',
    secondReadingRef: '1 John 3:1-2',
    oneLineTheme: '"I am the Good Shepherd who lays down his life for the sheep"',
  },
  {
    slug: '5th-sunday-easter',
    sundayName: '5th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 15:1-8',
    firstReadingRef: 'Acts 9:26-31',
    psalmRef: 'Ps 22',
    secondReadingRef: '1 John 3:18-24',
    oneLineTheme: '"I am the true vine — remain in me and you will bear much fruit"',
  },
  {
    slug: '6th-sunday-easter',
    sundayName: '6th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 15:9-17',
    firstReadingRef: 'Acts 10:25-26, 34-35, 44-48',
    psalmRef: 'Ps 98',
    secondReadingRef: '1 John 4:7-10',
    oneLineTheme: '"Love one another as I have loved you — greater love has no one than this"',
  },
  {
    slug: 'ascension-of-the-lord',
    sundayName: 'Ascension of the Lord',
    season: 'Easter',
    gospelRef: 'Mark 16:15-20',
    firstReadingRef: 'Acts 1:1-11',
    psalmRef: 'Ps 47',
    secondReadingRef: 'Eph 1:17-23',
    oneLineTheme: '"Go into the whole world and proclaim the Gospel to every creature"',
  },
  {
    slug: '7th-sunday-easter',
    sundayName: '7th Sunday of Easter',
    season: 'Easter',
    gospelRef: 'John 17:11b-19',
    firstReadingRef: 'Acts 1:15-17, 20a, 20c-26',
    psalmRef: 'Ps 103',
    secondReadingRef: '1 John 4:11-16',
    oneLineTheme: 'Jesus prays for the disciples — "Keep them in your name; consecrate them in truth"',
  },
  {
    slug: 'pentecost-sunday',
    sundayName: 'Pentecost Sunday',
    season: 'Easter',
    gospelRef: 'John 20:19-23',
    firstReadingRef: 'Acts 2:1-11',
    psalmRef: 'Ps 104',
    secondReadingRef: '1 Cor 12:3b-7, 12-13',
    oneLineTheme: '"Receive the Holy Spirit — whose sins you forgive are forgiven"',
    sameEveryYear: true,
  },
  // ORDINARY TIME II
  {
    slug: '10th-sunday-ordinary-time',
    sundayName: '10th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 3:20-35',
    firstReadingRef: 'Gen 3:9-15',
    psalmRef: 'Ps 130',
    secondReadingRef: '2 Cor 4:13–5:1',
    oneLineTheme: 'Jesus and Beelzebul — "Whoever does the will of God is my brother and sister"',
  },
  {
    slug: '11th-sunday-ordinary-time',
    sundayName: '11th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 4:26-34',
    firstReadingRef: 'Ezek 17:22-24',
    psalmRef: 'Ps 92',
    secondReadingRef: '2 Cor 5:6-10',
    oneLineTheme: 'The seed grows by itself and the mustard seed — the hidden power of the Kingdom',
  },
  {
    slug: '12th-sunday-ordinary-time',
    sundayName: '12th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 4:35-41',
    firstReadingRef: 'Job 38:1, 8-11',
    psalmRef: 'Ps 107',
    secondReadingRef: '2 Cor 5:14-17',
    oneLineTheme: '"Silence! Be still!" — Jesus calms the storm; "Who is this man?"',
  },
  {
    slug: '13th-sunday-ordinary-time',
    sundayName: '13th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 5:21-43',
    firstReadingRef: 'Wis 1:13-15; 2:23-24',
    psalmRef: 'Ps 30',
    secondReadingRef: '2 Cor 8:7, 9, 13-15',
    oneLineTheme: 'Jairus\'s daughter and the bleeding woman — "Your faith has saved you"',
  },
  {
    slug: '14th-sunday-ordinary-time',
    sundayName: '14th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 6:1-6',
    firstReadingRef: 'Ezek 2:2-5',
    psalmRef: 'Ps 123',
    secondReadingRef: '2 Cor 12:7-10',
    oneLineTheme: 'Rejected at Nazareth — "A prophet is not accepted in his hometown"',
  },
  {
    slug: '15th-sunday-ordinary-time',
    sundayName: '15th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 6:7-13',
    firstReadingRef: 'Amos 7:12-15',
    psalmRef: 'Ps 85',
    secondReadingRef: 'Eph 1:3-14',
    oneLineTheme: 'Sending out the Twelve — take nothing for the journey; preach repentance',
  },
  {
    slug: '16th-sunday-ordinary-time',
    sundayName: '16th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 6:30-34',
    firstReadingRef: 'Jer 23:1-6',
    psalmRef: 'Ps 23',
    secondReadingRef: 'Eph 2:13-18',
    oneLineTheme: '"Come away and rest a while" — Jesus the Good Shepherd has compassion on the crowd',
  },
  {
    slug: '17th-sunday-ordinary-time',
    sundayName: '17th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 6:1-15',
    firstReadingRef: '2 Kgs 4:42-44',
    psalmRef: 'Ps 145',
    secondReadingRef: 'Eph 4:1-6',
    oneLineTheme: 'Feeding of the 5,000 (John\'s version) — five loaves, two fish, twelve baskets left over',
  },
  {
    slug: '18th-sunday-ordinary-time',
    sundayName: '18th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 6:24-35',
    firstReadingRef: 'Exod 16:2-4, 12-15',
    psalmRef: 'Ps 78',
    secondReadingRef: 'Eph 4:17, 20-24',
    oneLineTheme: '"I am the bread of life — whoever comes to me will never hunger or thirst"',
  },
  {
    slug: '19th-sunday-ordinary-time',
    sundayName: '19th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 6:41-51',
    firstReadingRef: '1 Kgs 19:4-8',
    psalmRef: 'Ps 34',
    secondReadingRef: 'Eph 4:30–5:2',
    oneLineTheme: '"I am the living bread come down from heaven — eat and live forever"',
  },
  {
    slug: '20th-sunday-ordinary-time',
    sundayName: '20th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 6:51-58',
    firstReadingRef: 'Prov 9:1-6',
    psalmRef: 'Ps 34',
    secondReadingRef: 'Eph 5:15-20',
    oneLineTheme: '"My flesh is true food and my blood true drink" — the Eucharistic discourse',
  },
  {
    slug: '21st-sunday-ordinary-time',
    sundayName: '21st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'John 6:60-69',
    firstReadingRef: 'Josh 24:1-2a, 15-17, 18b',
    psalmRef: 'Ps 34',
    secondReadingRef: 'Eph 5:21-32',
    oneLineTheme: '"To whom shall we go? You have the words of eternal life" — Peter\'s confession',
  },
  {
    slug: '22nd-sunday-ordinary-time',
    sundayName: '22nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 7:1-8, 14-15, 21-23',
    firstReadingRef: 'Deut 4:1-2, 6-8',
    psalmRef: 'Ps 15',
    secondReadingRef: 'Jas 1:17-18, 21b-22, 27',
    oneLineTheme: 'Traditions and commandments — "You honour me with your lips but your heart is far"',
  },
  {
    slug: '23rd-sunday-ordinary-time',
    sundayName: '23rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 7:31-37',
    firstReadingRef: 'Isa 35:4-7a',
    psalmRef: 'Ps 146',
    secondReadingRef: 'Jas 2:1-5',
    oneLineTheme: '"Ephphatha! — Be opened!" — healing of the deaf man with a speech impediment',
  },
  {
    slug: '24th-sunday-ordinary-time',
    sundayName: '24th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 8:27-35',
    firstReadingRef: 'Isa 50:5-9a',
    psalmRef: 'Ps 116',
    secondReadingRef: 'Jas 2:14-18',
    oneLineTheme: '"Who do you say that I am?" — Peter\'s confession; "Take up your cross"',
  },
  {
    slug: '25th-sunday-ordinary-time',
    sundayName: '25th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 9:30-37',
    firstReadingRef: 'Wis 2:12, 17-20',
    psalmRef: 'Ps 54',
    secondReadingRef: 'Jas 3:16–4:3',
    oneLineTheme: '"Who is greatest?" — Jesus sets a child in their midst; serve, do not dominate',
  },
  {
    slug: '26th-sunday-ordinary-time',
    sundayName: '26th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 9:38-43, 45, 47-48',
    firstReadingRef: 'Num 11:25-29',
    psalmRef: 'Ps 19',
    secondReadingRef: 'Jas 5:1-6',
    oneLineTheme: '"Whoever is not against us is for us" — stumbling blocks and radical discipleship',
  },
  {
    slug: '27th-sunday-ordinary-time',
    sundayName: '27th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 10:2-16',
    firstReadingRef: 'Gen 2:18-24',
    psalmRef: 'Ps 128',
    secondReadingRef: 'Heb 2:9-11',
    oneLineTheme: 'On marriage and divorce; receiving the Kingdom like a child',
  },
  {
    slug: '28th-sunday-ordinary-time',
    sundayName: '28th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 10:17-30',
    firstReadingRef: 'Wis 7:7-11',
    psalmRef: 'Ps 90',
    secondReadingRef: 'Heb 4:12-13',
    oneLineTheme: 'The Rich Young Man — "Sell what you have; it is easier for a camel through a needle\'s eye"',
  },
  {
    slug: '29th-sunday-ordinary-time',
    sundayName: '29th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 10:35-45',
    firstReadingRef: 'Isa 53:10-11',
    psalmRef: 'Ps 33',
    secondReadingRef: 'Heb 4:14-16',
    oneLineTheme: '"The Son of Man came to serve, not to be served, and to give his life as a ransom"',
  },
  {
    slug: '30th-sunday-ordinary-time',
    sundayName: '30th Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 10:46-52',
    firstReadingRef: 'Jer 31:7-9',
    psalmRef: 'Ps 126',
    secondReadingRef: 'Heb 5:1-6',
    oneLineTheme: 'Bartimaeus: "Son of David, have pity on me!" — "Your faith has saved you"',
  },
  {
    slug: '31st-sunday-ordinary-time',
    sundayName: '31st Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 12:28b-34',
    firstReadingRef: 'Deut 6:2-6',
    psalmRef: 'Ps 18',
    secondReadingRef: 'Heb 7:23-28',
    oneLineTheme: '"The scribe was not far from the Kingdom" — the double commandment of love',
  },
  {
    slug: '32nd-sunday-ordinary-time',
    sundayName: '32nd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 12:38-44',
    firstReadingRef: '1 Kgs 17:10-16',
    psalmRef: 'Ps 146',
    secondReadingRef: 'Heb 9:24-28',
    oneLineTheme: 'The widow\'s mite — she gave from her poverty, everything she had',
  },
  {
    slug: '33rd-sunday-ordinary-time',
    sundayName: '33rd Sunday of Ordinary Time',
    season: 'OrdinaryTime',
    gospelRef: 'Mark 13:24-32',
    firstReadingRef: 'Dan 12:1-3',
    psalmRef: 'Ps 16',
    secondReadingRef: 'Heb 10:11-14, 18',
    oneLineTheme: 'Signs of the end — "The Son of Man coming in clouds with great power and glory"',
  },
  {
    slug: 'christ-the-king',
    sundayName: '34th Sunday — Our Lord Jesus Christ, King of the Universe',
    season: 'OrdinaryTime',
    gospelRef: 'John 18:33b-37',
    firstReadingRef: 'Dan 7:13-14',
    psalmRef: 'Ps 93',
    secondReadingRef: 'Rev 1:5-8',
    oneLineTheme: '"My kingdom is not of this world" — Pilate meets the King of truth',
  },
]

export default yearB
